package guru.springfamework.api.v1.mapper;

import guru.springfamework.domain.Customer;

import guru.springfamework.model.CustomerDTO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper
/*
* Dont forget to build with maven so the mapper class is autogenerated.
* Otherwhise it will not be injected
* Is located in target -> classes/guru/springfamework/api/v1/mapper
* */
public interface CustomerMapper {

    CustomerMapper INSTANCE = Mappers.getMapper(CustomerMapper.class);

    //@Mapping(source = "id", target = "id") //-> Not needed.
    //@Mapping(source = "name", target = "name") // -> Not needed.
    CustomerDTO customerToCustomerDTO(Customer customer);

    Customer customerDtoToCustomer (CustomerDTO customerDTO);

}
